name: 'Yarn 2 Install'
description: 'Install yarn 2 with caching'
runs:
  using: 'composite'
  steps:
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      shell: bash
      run: echo "dir=$(cd client && yarn config get cacheFolder)" >> $GITHUB_ENV

    - name: Cache Dependencies
      uses: actions/cache@v3
      with:
        path: ${{ env.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - run: yarn install
      shell: bash
