openapi: '3.0.0'
info:
  version: 1.0.0
  title: Data Loader
  description: An app for loading data from different sources
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:3100

paths:
  '/.well-known/health-check':
    get:
      summary: Health Check
      description: Health check endpoint
      tags:
        - well-known
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: { $ref: '#/components/schemas/HealthCheck' }
      operationId: get-well-known-health-check

  '/.well-known/openapi.yaml':
    get:
      summary: API Docs
      description: The open api spec for the service. OpenAPI v3.
      tags:
        - well-known
      responses:
        '200':
          description: HTML Representation of the reset API
          content:
            application/yaml:
              schema: { type: string }

  '/v1/meter-reads':
    parameters:
      - { $ref: '#/components/parameters/traceToken' }
      - { $ref: '#/components/parameters/serialNumber' }
      - { $ref: '#/components/parameters/date' }
    get:
      security: [{ BearerAuth: ['read'] }]
      summary: Meter Reads
      description: Retern meter reads
      responses:
        '200':
          description: Meter Reads list
          content:
            application/json:
              schema:
                items: { $ref: '#/components/schemas/MeterRead' }

  '/v1/hydration/meter-reads':
    parameters:
      - { $ref: '#/components/parameters/traceToken' }
    post:
      security: [{ BearerAuth: ['update'] }]
      summary: Meter reads csv upload
      requestBody:
        content:
          text/csv:
            schema:
              type: string
              format: binary
      description: |
        Upload a csv meter reads.
      responses:
        '500': { $ref: '#/components/responses/HttpErrorResponse' }
        '400': { $ref: '#/components/responses/HttpErrorResponse' }
        '200': { $ref: '#/components/responses/SuccessResponse' }

components:
  # Responses
  # ==================================================================

  responses:
    HttpErrorResponse:
      description: Unkown Error
      content:
        application/json:
          schema: { $ref: '#/components/schemas/HttpError' }

    SuccessResponse:
      description: |
        A generic success response
      content:
        application/json:
          schema:
            additionalProperties: false
            properties:
              success:
                type: boolean
            required:
              - success
  # Parameters
  # ==================================================================

  parameters:
    traceToken:
      name: X-Trace-Token
      in: header
      description: An optional trace token to be passed to the service and used for logging
      schema:
        type: string
        format: uuid

    serialNumber:
      name: serialNumber
      in: query
      description: Filter by serial number
      schema:
        type: string

    date:
      name: date
      in: query
      description: Filter by date
      schema:
        type: string
        format: date

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

  schemas:
    HttpError:
      additionalProperties: false
      properties:
        message: { type: 'string' }

    HealthCheck:
      additionalProperties: false
      properties:
        healthy: { type: 'boolean' }
      required:
        - healthy

    MeterRead:
      additionalProperties: false
      properties:
        serialNumber: { type: string }
        value: { type: string }
        date: { type: string, format: date-time }
      required:
        - serialNumber
        - value
        - date
