name: 'Update Git Submodules'
description: 'Checkout all git submodule repositories'
runs:
  using: 'composite'
  steps:
    - run: git submodule sync
      shell: bash
    - run: git submodule update --init
      shell: bash
