name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: adambirds/docker-compose-action@v1.3.0
      - uses: actions/setup-node@v2
        with:
          node-version: '18.18.2'
      - uses: ./.github/actions/yarn-install
      - run: yarn build
      - run: yarn lint
      - run: yarn test --runInBand --ci
